// This file is generated by Astro DB
declare module 'astro:db' {
	export const Contacts: import("@astrojs/db/runtime").Table<
		"Contacts",
		{"name":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"name","collection":"Contacts","primaryKey":false,"optional":false}},"email":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"email","collection":"Contacts","primaryKey":false,"optional":false}},"phone":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"phone","collection":"Contacts","primaryKey":false,"optional":false}},"message":{"type":"text","schema":{"unique":false,"deprecated":false,"name":"message","collection":"Contacts","primaryKey":false,"optional":false}}}
	>;
}
